name: deploy
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [gatsby_build]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
      - run: git config --global user.name ${{ secrets.NAME }}
      - run: git config --global user.email ${{ secrets.E_MAIL }}
      - run: git remote set-url origin https://github.com/odaka-yuki/web-basic-knowledge.git
      - run: npm ci
      - run: npm run deploy
