name: deploy
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [gatsby_build]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run deploy
